"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.28.
"""

import os
import re
import sys
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()


BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Env parsing helpers
# ---------------------------------------------------------------------------

_TRUE_TOKENS = frozenset({"1", "true", "yes", "on", "y", "t"})
_SPLIT_RE = re.compile(r"[,\s]+")


def env_bool(name, default=False):
    """Parse an env var as a boolean.

    Accepts 1/true/yes/on/y/t (case-insensitive) as truthy; anything else is false.
    Missing var returns ``default``.
    """
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in _TRUE_TOKENS


def env_list(name, default=None):
    """Parse an env var as a list, splitting on commas AND whitespace.

    Empty entries are dropped. Missing var returns ``default`` (or ``[]``).
    """
    raw = os.environ.get(name)
    if raw is None:
        return list(default) if default is not None else []
    return [item for item in _SPLIT_RE.split(raw) if item]


# ---------------------------------------------------------------------------
# Core settings
# ---------------------------------------------------------------------------

is_test_command = "test" in sys.argv

DEBUG = env_bool("DEBUG", default=False)

_secret_key = os.environ.get("SECRET_KEY")
if not _secret_key:
    if not DEBUG and not is_test_command:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable is required when DEBUG is disabled."
        )
    _secret_key = "django-insecure-dev-only-do-not-use-in-prod"
SECRET_KEY = _secret_key

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1", "[::1]", "web"],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_celery_results',

    # Local apps
    'core',
    'analysis',
    'projects',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.ThreadLocalMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database

if os.environ.get("SQL_ENGINE"):
    db_engine = os.environ.get("SQL_ENGINE")
    db_name = os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3")
    db_user = os.environ.get("SQL_USER", "user")
    db_password = os.environ.get("SQL_PASSWORD", "password")
    db_host = os.environ.get("SQL_HOST", "db")
    db_port = os.environ.get("SQL_PORT", "5432")
elif os.environ.get("POSTGRES_DB") and not is_test_command:
    db_engine = "django.db.backends.postgresql"
    db_name = os.environ.get("POSTGRES_DB", "biodjango")
    db_user = os.environ.get("POSTGRES_USER", "postgres")
    db_password = os.environ.get("POSTGRES_PASSWORD", "")
    db_host = os.environ.get("POSTGRES_HOST", "127.0.0.1")
    db_port = os.environ.get("POSTGRES_PORT", "5432")
else:
    db_engine = "django.db.backends.sqlite3"
    db_name = BASE_DIR / "db.sqlite3"
    db_user = ""
    db_password = ""
    db_host = ""
    db_port = ""

DATABASES = {
    'default': {
        'ENGINE': db_engine,
        'NAME': db_name,
        'USER': db_user,
        'PASSWORD': db_password,
        'HOST': db_host,
        'PORT': db_port,
    }
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files

STATIC_URL = '/django_static/'
STATIC_ROOT = BASE_DIR / "static"


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# DRF & JWT
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '120/min',
        'task_poll': '600/min',
        'anon_register': '5/day',
    },
}

if env_bool('ENABLE_PAGINATION', default=False):
    REST_FRAMEWORK['DEFAULT_PAGINATION_CLASS'] = (
        'rest_framework.pagination.PageNumberPagination'
    )
    REST_FRAMEWORK['PAGE_SIZE'] = 50

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# ---------------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------------

CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    default=["http://localhost:5173", "http://localhost:3000"],
)


# ---------------------------------------------------------------------------
# Celery
# ---------------------------------------------------------------------------

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_TASK_ALWAYS_EAGER = env_bool("CELERY_TASK_ALWAYS_EAGER", default=False)
CELERY_TASK_EAGER_PROPAGATES = env_bool("CELERY_TASK_EAGER_PROPAGATES", default=True)


# ---------------------------------------------------------------------------
# BLAST DB path
# ---------------------------------------------------------------------------

BLAST_DB_PATH = os.environ.get("BLAST_DB_PATH", "/data/blastdb")


# ---------------------------------------------------------------------------
# Caches
# ---------------------------------------------------------------------------

if is_test_command:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'biodjango-tests',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.environ.get('REDIS_CACHE_URL', CELERY_BROKER_URL),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
        }
    }


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

_log_console_formatter = 'verbose' if DEBUG else 'json'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s %(name)s %(module)s: %(message)s',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': (
                '%(asctime)s %(levelname)s %(name)s %(module)s %(funcName)s '
                '%(lineno)d %(message)s'
            ),
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': _log_console_formatter,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'analysis': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'projects': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'core': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'django.request': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
    },
}
