# Generated by Django 4.2.28 on 2026-02-19 09:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(help_text='Unique identifier for the project', max_length=50, unique=True)),
                ('security_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DNA_Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('name', models.CharField(blank=True, help_text='Optional name for the sequence', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dna_sequences', to='core.project')),
            ],
            options={
                'verbose_name': 'DNA Sequence',
                'verbose_name_plural': 'DNA Sequences',
            },
        ),
        migrations.CreateModel(
            name='AA_Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('name', models.CharField(blank=True, help_text='Optional name for the sequence', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aa_sequences', to='core.project')),
            ],
            options={
                'verbose_name': 'AA Sequence',
                'verbose_name_plural': 'AA Sequences',
            },
        ),
    ]
